### ISSUE TITLE
rustls pemfile do not open encrypted private key

### ISSUE THREAD

**Issue by gustavowd** [rustls/pemfile#15]
I'm trying to open a encrypted private key with the rustls_pemfile lib, but i am always receiving a empty vector.
I used this command to generate the encrypt private key:
openssl genrsa -aes-128-cbc -out ca.key 2048

A encrypted private key has a password. Is there any way to open this kind of private key passing the password in this lib?

The file init is:
-----BEGIN ENCRYPTED PRIVATE KEY-----

That's important, because new standards, such as modbus security, has the default chiper TLS_RSA_WITH_AES_128_CBC_SHA256, which is encrypted.

Thanks in advance

**Comment by cpu** [comment]
Hello @gustavowd,

> Is there any way to open this kind of private key passing the password in this lib?

There's no support for reading encrypted private key information in this library at the current time.

> That's important, because new standards, such as modbus security, has the default chiper TLS_RSA_WITH_AES_128_CBC_SHA256, which is encrypted.

Do you have a citation to the standard you're trying to meet? In my experience it's unusual to password protect keys for TLS because of the operational issues it creates trying to have your server software access the key material it needs at startup/restart.

**Comment by jadamcrain** [comment]
Modbus security does not require encryption of key materials at rest.  That's just the default cipher suite.

You can use the [pkcs8](https://crates.io/crates/pkcs8) crate to decrypt keys before passing them to rustls as we've done in our secure modbus implementation [here](https://github.com/stepfunc/rodbus/blob/7bff2966a4a4a82adcb838cff628ec4073f52a02/rodbus/src/tcp/tls/mod.rs#L216).

We had to do this because customers had pre-existing PKIs that already used encrypted PEM files.

**Comment by hwadii** [comment]
What would it take to implement this? I'm interested in implementing support for password encrypted pemfiles in [reqwest](https://github.com/seanmonstar/reqwest) for [xh](https://github.com/ducaale/xh), reqwest uses this library to parse pemfiles.

**Comment by djc** [comment]
Did you read the comment above? Is decrypting the keys using the pkcs8 crate a viable option for you?

**Comment by hwadii** [comment]
> Is decrypting the keys using the pkcs8 crate a viable option for you?

I guess so. reqwest uses this library exclusively to parse pemfiles, and trying to parse an encrypted private key yields an empty vector. I will however try to explore that path. Thanks

**Comment by cpu** [comment]
I think we should consider this out-of-scope for `pemfile` since the `pkcs8` crate exists and can meet the need.
