### ISSUE TITLE
Incorrect parsing of private key by rustls_pemfile::private_key

### ISSUE THREAD

**Issue by darkseid-is** [rustls/pemfile#39]
1. The private_key read from the file is of type PrivateKeyDer::Pkcs8(PrivatePkcs1KeyDer(...))
2. The private_key and key added using include_str! doesn't assert 

Generate Private Key
```bash
openssl genrsa -out private.key 2048
```

```rust
use std::{fs::File, io::BufReader};
use rustls::pki_types::{PrivateKeyDer, PrivatePkcs1KeyDer, PrivatePkcs8KeyDer};

const PRIVATE_KEY: &str = include_str!("./private.key");

fn main() {
    let private_key_file = "./private.key";
    let private_key: PrivateKeyDer = rustls_pemfile::private_key(&mut BufReader::new(&mut File::open(private_key_file).unwrap())).unwrap().unwrap();
    dbg!(&private_key); // Pkcs8(PrivatePkcs1KeyDer(..)) ?

    let new_key: PrivatePkcs8KeyDer = PRIVATE_KEY.as_bytes().into();
    let new_key_as_enum: PrivateKeyDer  = new_key.into();
    dbg!(&new_key_as_enum);
    assert_eq!(private_key, new_key_as_enum); // Assertion Failed
}
```

**Comment by ctz** [comment]
> `    dbg!(&private_key); // Pkcs8(PrivatePkcs1KeyDer(..)) ?`

For me this line is:

```
[tmp/pemfile-test/src/main.rs:13] &private_key = Pkcs1(
    PrivatePkcs1KeyDer(
        "[secret key elided]",
    ),
)
```

> `    let new_key: PrivatePkcs8KeyDer = PRIVATE_KEY.as_bytes().into();`

`PRIVATE_KEY` here is a string containing the PEM-formatted PKCS#1 format file. Then `.as_bytes()` gives you that string as UTF-8 bytes[^1], then `.into()` takes that and assumes it is DER-encoded (it isn't!) PKCS-8 encoding (it isn't!).

> `    let new_key_as_enum: PrivateKeyDer  = new_key.into();`
> `    dbg!(&new_key_as_enum);`

This is `impl<'a> From<PrivatePkcs8KeyDer<'a>> for PrivateKeyDer<'a>`, but the result prints:

```
[tmp/pemfile-test/src/main.rs:17] &new_key_as_enum = Pkcs8(
    PrivatePkcs1KeyDer(
        "[secret key elided]",
    ),
)
```

(this bug was fixed recently in https://github.com/rustls/pki-types/commit/62612f3bf9d3d61ef1d23370e68c86243ef8c188; the type name is printed incorrectly and the type is actually `PrivatePkcs8KeyDer`.)

[^1]: https://doc.rust-lang.org/std/primitive.str.html#method.as_bytes

**Comment by ctz** [comment]
Both. The library bug is fixed in https://crates.io/crates/rustls-pki-types/1.3.1 and relates only to the formatting of debug output. The main issue with your code is the second part does not use `rustls_pemfile` at all, even though the data it is processing is PEM-encoded.

**Comment by darkseid-is** [comment]
Line 2 in main fn 

`rustls_pemfile::private_key -> rustls_pki_types::PrivateKeyDer::Pkcs8`

Line 6,7 

` &[u8] -> rustls_pki_types::PrivatePkcs8KeyDer ->  rustls_pki_types::PrivateKeyDer::Pkcs8`

Ignore the debug statement , shouldn't the assertion succeed ?

**Comment by djc** [comment]
No, because `rustls_pemfile::private_key()` doesn't just wrap the bytes from your file in a separate type, it also parses the contents of your file (which are in PEM format) into DER. For `new_key` you are nonsensically wrapping the PEM contents in a data type intended to only hold DER data, so while that satisfies the type system it doesn't result in the same data.

**Comment by darkseid-is** [comment]
There is a trait implementation from &[u8] for PrivatePkcs8KeyDer. So there I thought into() should return PrivatePkcs8KeyDer. But, sadly From<&[u8]> doesn't perform any checks. @djc What is nonsensical about this?.

Shouldn't the from implementation be like,

&str -> &[u8] -> rustls_pemfile::read_one_from_slice -> rustls_pemfile::Item -> rustls_pki_types::PrivateKeyDer
